version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - API_PORT=${API_PORT}
      - FRONT_END_URL=${FRONT_END_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${API_PORT}:${API_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    network_mode: bridge
